version: '3.1'

services:
  node:
    image: registry.gitlab.com/t-x-t/karmabot:master
    restart: always
    volumes:
      - "/opt/karmabot/config.prod.json:/srv/karmabot/config.prod.json"
    links:
      - redis
    networks:
      - data
      - nginx
  redis:
    image: redis
    restart: always
    volumes:
      - "/opt/karmabot/redis.conf:/usr/local/etc/redis/redis.conf"
      - "/opt/karmabot/redisdata:/data"
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      - data

networks:
  data:
    driver: "bridge"
  nginx:
    external: true