name: Build, test and push

on:
  push:
    branches:
      - "**"

jobs:
  build_server_docker_image:
      runs-on: vm
      container:
        image: git.thetxt.io/thetxt/runner-base:latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Build server image
          env:
            IMAGE_TAG: git.thetxt.io/thetxt/karmabot:${{ github.ref_name }}
          run: |
            nohup dockerd-entrypoint.sh &
            sleep 5
            docker build -t $IMAGE_TAG .
        - name: Push server image
          env:
            IMAGE_TAG: git.thetxt.io/thetxt/karmabot:${{ github.ref_name }}
          run: docker push $IMAGE_TAG
